//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace ProyectoIntegrador.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Cliente
    {
        [Required(ErrorMessage = "Cédula es requerido.")]
        [MaxLength(30)]
        public string cedulaPK { get; set; }

        [Required(ErrorMessage = "Nombre es requerido.")]
        [MaxLength(30, ErrorMessage = "Sobrepaso el limite para el nombre.")]
        public string nombre { get; set; }

        [Required(ErrorMessage = "Primer Apellido es requerido.")]
        [MaxLength(30, ErrorMessage = "Sobrepaso el limite para el apellido.")]
        public string apellido1 { get; set; }

        [MaxLength(30, ErrorMessage = "Sobrepaso el limite para el segundo apellido.")]
        public string apellido2 { get; set; }

        [Required(ErrorMessage = "Empresa es requerido.")]
        [MaxLength(30, ErrorMessage = "Sobrepaso el limite para el nombre de empresa.")]
        public string empresa { get; set; }

        [Required(ErrorMessage = "Provincia es requerido.")]
        public string provincia { get; set; }

        [Required(ErrorMessage = "Canton es requerido.")]
        public string canton { get; set; }

        [Required(ErrorMessage = "Distrito es requerido.")]
        public string distrito { get; set; }

        [MaxLength(300, ErrorMessage = "Sobrepaso el limite para la dirección.")]
        public string direccionExacta { get; set; }

        [DataType(DataType.PhoneNumber)]
        [MaxLength(15, ErrorMessage = "Sobrepaso el limite para el telefono.")]
        public string telefono { get; set; }

        [Required(ErrorMessage = "Correo es requerido.")]
        [DataType(DataType.EmailAddress)]
        [MaxLength(50, ErrorMessage = "Sobrepaso el limite para el correo.")]
        public string correo { get; set; }
    }
}
