//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIntegrador.BaseDatos
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class HabilidadBlanda
    {
        [Key]
        public string idEmpleadoFK { get; set; }
        [Key]
        public string habilidad { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
