//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIntegrador.BaseDatos
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class HistorialReqTester
    {
        [Key]
        public int idProyectoFK { get; set; }
        [Key]
        public int idReqFK { get; set; }
        [Key]
        public string idEmpleadoFK { get; set; }
        public Nullable<int> horas { get; set; }
        [Key]
        public System.DateTime fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public string estado { get; set; } = "Activo";
    
        public virtual Tester Tester { get; set; }
        public virtual Requerimiento Requerimiento { get; set; }
    }
}
