//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIntegrador.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyecto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proyecto()
        {
            this.Requerimientoes = new HashSet<Requerimiento>();
            this.TrabajaEns = new HashSet<TrabajaEn>();
        }
    
        public int idProyectoAID { get; set; }
        public string nombre { get; set; }
        public string objetivo { get; set; }
        public string estado { get; set; } = "Preparacion";
        public System.TimeSpan duracionReal { get; set; }= TimeSpan.Zero;
        public System.TimeSpan duracionEstimada { get; set; } = TimeSpan.Zero;
        public System.DateTime fechaInicio { get; set; } = DateTime.Now.Date;
        public System.DateTime fechaFinalizacion { get; set; }=  DateTime.Parse("1800-01-01");
        public string cedulaClienteFK { get; set; }
        public int cantidadReq { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requerimiento> Requerimientoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrabajaEn> TrabajaEns { get; set; }
    }
}
