//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIntegrador.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prueba
    {
        public int idProyectoFK { get; set; }
        public int idReqFK { get; set; }
        public int idPruebaPK { get; set; }
        public string resultadoFinal { get; set; }
        public string propositoPrueba { get; set; }
        public string entradaDatos { get; set; }
        public string resultadoEsperado { get; set; }
        public string flujoPrueba { get; set; }
        public string estado { get; set; }
        public byte[] imagen { get; set; }
        public string descripcionError { get; set; }
    
        public virtual Requerimiento Requerimiento { get; set; }
    }
}
