//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIntegrador.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requerimiento
    {
        public int idReqPK { get; set; }
        public int idProyectoFK { get; set; }
        public string cedulaTesterFK { get; set; }
        public string nombre { get; set; }
        public string complejidad { get; set; }
        public int tiempoEstimado { get; set; }
        public Nullable<int> tiempoReal { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fechaDeInicio { get; set; }
        public Nullable<System.DateTime> fechaDeFinalizacion { get; set; }
        public string estado { get; set; }
        public Nullable<int> horas { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
