//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIntegrador.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeguridadProyectoAgregar
    {
        public int Rol { get; set; }
        public int Nombre { get; set; }
        public int Objetivo { get; set; }
        public int Estado { get; set; }
        public int DuracionEstimada { get; set; }
        public int DuracionReal { get; set; }
        public int FechaInicio { get; set; }
        public int FechaFin { get; set; }
        public int CedulaCliente { get; set; }
        public int CedulaLider { get; set; }
    }
}
