//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIntegrador.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeguridadEmpleadosGeneral
    {
        public int Rol { get; set; }
        public int Consultar { get; set; }
        public int Agregar { get; set; }
        public int Editar { get; set; }
        public int Eliminar { get; set; }
    }
}
